### ISSUE TITLE
Descriptor Input >> Descriptor Output Option tool

### ISSUE THREAD

**Issue by Purg** [mryoo/pooled_time_series#3]
For SMQTK integration purposes, we would need to have an interface where we could giving a set of arbitrary, temporally related/ordered descriptors to the pooled time series algorithm, and get back the single descriptor that is the output.

From my discussion with Michael, I interpreted this as possible given the current implementation of the underlying algorithm.

This would allow SMQTK to handle the scaling (17m^2 distance kernel not feasible) and similarity computation outside of this implementation.

This could/should be a separate tool/executable.

**Comment by chrismattmann** [comment]
this issue has been open for 9+ months, closing for now, and will revisit later.
